### ISSUE TITLE
Secrets pushed to repo

### ISSUE THREAD

**Issue by beingke** [alexryanjones/games#1]
Hope you are well @alexryanjones!

Quick headsup: 
- Server [.env file](https://github.com/alexryanjones/games/blob/main/server/.env) was pushed to the repo and is currently displaying secrets publicly.
- I would suggest to fully remove this (from the repo's and repo's history).

Best,
beingke.

**Comment by alexryanjones** [comment]
Hey beingke,

Thanks for the heads up, this has now been removed.

Cheers!
